CC=gcc
RCC=gcc
#PROFILEROPT=-pg
PROFILEROPT=
MEX=mex
OPTDEF=-DUSE_LPOPT_WARM_START=1
#OPTDEF=
#OPTIMIZATION=-g
OPTIMIZATION=-O3
CFLAGS=-c -Wall $(OPTIMIZATION) -fPIC $(OPTDEF) $(PROFILEROPT)
MFLAGS=-lgfortran
LDFLAGS=-lgfortran $(OPTIMIZATION) $(PROFILEROPT)
SOURCES=perplex.c 
MSOURCES=m_ini_phaseq.c
RSOURCES=Rperplex.c
RCFLAGS=-I/usr/share/R/include -std=gnu99
RLDFLAGS=-L/usr/lib/R/lib -lR
OBJECTS=$(SOURCES:.c=.o)
ROBJECTS=$(RSOURCES:.c=.o)
RSHLIB=$(RSOURCES:.c=.so)
SHLIB=libperplex.so
#PERPLEXSRC=/home/julienko/Desktop/Perple_X_6.8.1_source/perplex-stable
PERPLEXSRC=../perplex-stable
PERPLEXOBJECTS=$(PERPLEXSRC)/meemum.o $(PERPLEXSRC)/getxz1.o $(PERPLEXSRC)/dumlib.o $(PERPLEXSRC)/resub.o $(PERPLEXSRC)/nlib.o $(PERPLEXSRC)/olib.o $(PERPLEXSRC)/clib.o $(PERPLEXSRC)/rlib.o $(PERPLEXSRC)/tlib.o $(PERPLEXSRC)/flib.o
#PERPLEXOBJECTS=
EXECUTABLE=

all: $(OBJECTS) $(ROBJECTS) $(SHLIB) $(RSHLIB)

clean:
	rm -f $(OBJECTS) $(ROBJECTS) $(RSHLIB) $(EXECUTABLE)

Robj: $(RSOURCES) $(PERPLEXOBJECTS)
	$(CC) $(CFLAGS) $(RCFLAGS) $(RSOURCES)

obj: $(SOURCES) $(PERPLEXOBJECTS) 
	$(CC) $(CFLAGS) $(SOURCES)

shared: $(OBJECTS)
	$(CC) $(OPTIMIZATION) -shared -o $(SHLIB) $(OBJECTS)

Rshared: $(OBJECTS) $(ROBJECTS) $(PERPLEXOBJECTS)
	$(RCC) -shared -o $(RSHLIB) $(ROBJECTS) $(OBJECTS) $(PERPLEXOBJECTS) $(LDFLAGS) $(RLDFLAGS)


matlab: $(OBJECTS) $(PERPLEXOBJECTS) $(MSOURCES)
	/usr/local/MATLAB/R2017b/bin/mex $(MFLAGS) $(MSOURCES) $(OBJECTS) $(PERPLEXOBJECTS)

$(EXECUTABLE): $(OBJECTS) $(PERPLEXOBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) $(PERPLEXOBJECTS) -o $@

	#.c.o:
	#$(CC) $(CFLAGS) $< -o $@

