#include <stdio.h>
#include <malloc.h>
#include <string.h>
#include "perplex.h"

/* This example will use PerpleX wrapper to evaluate
   the stable phases of given compositions (array 'comp'
   below) in pressure-temperature range from 1 bar/1373 K
   to 35 kbar/2173 K, and output them to output.csv 

   To run this example, do:
     $ make
     $ cd datfiles
     $ ../gridding
   Output will be to output.csv

*/

int main(int argc, char **argv) {
	double P, T;
	int ncomp;
	double *comp;
	int i, j, row;

	FILE *fp;

	double p1, p2, t1, t2;
	double dp, dt;
	
	int nphases;
	double *wtphases = 0;
	double *cphases = 0;
	char *namephases = 0;
	double *sysprop = 0;
	double *phsysprop = 0;

	char *compnames = 0;
	double *compvalues = 0;
	int *comp_match_table = 0;
	int *r_comp_match_table = 0;

	int phaseq_dbg = 0; /* debug output from phaseq()? */
	
	/* only call once per build file */
	ini_phaseq("crustmod");	// filename (without .dat extension) 
	                                // generated by PerpleX BUILD.
					// If no path defined, it will be looked
					// for in the current folder where
					// this program is executed.
	
	p1 = 3000;
	p2 = 6000;
	t1 = 300+273;
	t2 = 600+273;

	dp = 250;
	dt = 20;	

	ncomp = 10;

	fp = fopen("output.csv", "w");
	if (fp == 0) {
		fprintf(stderr, "!! Failed to open output.csv\n");
		return -1;
	}
	comp = (double*)calloc(ncomp, sizeof(double));

	fprintf(fp, "\"P\",\"T\",\"phase\",\"phasewt\"");
	for (j = 0; j < ncomp; j++) {
		fprintf(fp, ",\"comp%d\"", j);
	}
	fprintf(fp, "\n");

	row = 0;

	wtphases = (double *)malloc(sizeof(double) * p_size_phases);
	cphases = (double *)malloc(sizeof(double) * p_size_phases * p_size_components);
	phsysprop = (double *)malloc(sizeof(double) * p_size_phases * p_size_sysprops);
	sysprop = (double *)malloc(sizeof(double) * p_size_sysprops);
	namephases = (char *)malloc(sizeof(char) * p_size_phases * p_pname_len);

    compnames = (char *)malloc(p_size_components * p_cname_len * sizeof(char *));
    comp_match_table = (int *)malloc(p_size_components * sizeof(int));
    r_comp_match_table = (int *)malloc(p_size_components * sizeof(int));

	compvalues = (double *)malloc(sizeof(double) * p_size_components);

	strncpy(compnames + 0*p_cname_len,   "NA2O ", sizeof(char) * p_cname_len-1); compvalues[0] = 0.0327;
	strncpy(compnames + 1*p_cname_len,   "MGO  ", sizeof(char) * p_cname_len-1); compvalues[1] = 0.0248;
	strncpy(compnames + 2*p_cname_len,   "AL2O3", sizeof(char) * p_cname_len-1); compvalues[2] = 0.1540;
	strncpy(compnames + 3*p_cname_len,   "SIO2 ", sizeof(char) * p_cname_len-1); compvalues[3] = 0.6662;
	strncpy(compnames + 4*p_cname_len,   "K2O  ", sizeof(char) * p_cname_len-1); compvalues[4] = 0.0280;
	strncpy(compnames + 5*p_cname_len,   "CAO  ", sizeof(char) * p_cname_len-1); compvalues[5] = 0.0359;
	strncpy(compnames + 6*p_cname_len,   "TIO2 ", sizeof(char) * p_cname_len-1); compvalues[6] = 0.0064;
	strncpy(compnames + 7*p_cname_len,   "MNO  ", sizeof(char) * p_cname_len-1); compvalues[7] = 0.0010;
	strncpy(compnames + 8*p_cname_len,   "FEO  ", sizeof(char) * p_cname_len-1); compvalues[8] = 0.0504;
	strncpy(compnames + 9*p_cname_len,   "H2O  ", sizeof(char) * p_cname_len-1); compvalues[9] = 0.0000;

	j = match_comp_order(compnames, comp_match_table, r_comp_match_table);
	
	
	fprintf(stdout, "match_comp_order(): %d\n", j);

	for (j = 0; j < ncomp; j++) {
        fprintf(stdout, "comp_match_table[%d] = %d\n", j, comp_match_table[j]);
	}

	for (j = 0; j < ncomp; j++) {
	    comp[comp_match_table[j]] = compvalues[j];
	    fprintf(stdout, "compnames[%d] == %.5s --> comp[%d] = %g\n", 
	        j, compnames+j*p_cname_len, comp_match_table[j], compvalues[j]);
	}



	for (P = p1; P <= p2; P += dp) {
		for (T = t1; T <= t2; T += dt) {
			fprintf(stderr, "\rP = %g   T = %g        ", P, T);

			phaseq(P, T, ncomp, comp, &nphases, wtphases, cphases, sysprop, phsysprop, namephases, phaseq_dbg);
	
			for (i = 0; i < nphases; i++) {
				row++;
				fprintf(fp, "%g,%g,", P, T);			// P , T ,
				fprintf(fp, "%.14s,", namephases + i*p_pname_len);	// name ,
				fprintf(fp, "%.5e", wtphases[i]);			// wt% ,
				for (j = 0; j < ncomp; j++) {
					fprintf(fp, ",%.5e", cphases[i*ncomp + j]);	// composition
				}
				fprintf(fp, "\n");
			}
		}
	}

	free(comp);
	fclose(fp);

	fprintf(stderr, "\n\n");
	
	return 0;
}

